### ISSUE TITLE
missing BeautifulSoup

### ISSUE THREAD

**Issue by alelondon** [jvasile/freedombox-privoxy#1]
Steps to reproduce:
git clone https://github.com/jvasile/freedombox-privoxy

cd freedombox-privoxy/  (BTW this step is missing in documentation)

make deb

output:

--2012-01-25 13:13:32--  https://easylist-downloads.adblockplus.org/easyprivacy.txt
WARNING: gnome-keyring:: couldn't connect to: /tmp/keyring-FMZWIg/pkcs11: No such file or directory
Resolving easylist-downloads.adblockplus.org (easylist-downloads.adblockplus.org)... 213.239.217.143
Connecting to easylist-downloads.adblockplus.org (easylist-downloads.adblockplus.org)|213.239.217.143|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 100728 (98K) [text/plain]
Saving to: `easyprivacy.txt'

100%[======================================>] 100,728      655K/s   in 0.2s    

2012-01-25 13:13:34 (655 KB/s) - `easyprivacy.txt' saved [100728/100728]

Unhandled options: donottrack, ~image
Unhandled options: domain=~informer.com.ip
Unhandled options: domain=~etahub.com.ip
Unhandled options: domain=~amazon.cdn.ip.seen.on.cheapflight
Unhandled options: object-subrequest
Unhandled options: ~image
Unhandled options: object-subrequest
Unhandled options: object-subrequest
Unhandled options: ~object-subrequest
Unhandled options: object-subrequest
Unhandled options: object-subrequest
Unhandled options: object-subrequest
Unhandled options: object-subrequest
Unhandled options: ~object-subrequest
Unhandled options: domain=~statistik.lubw.baden-wuerttemberg.de.ip
Unhandled options: domain=~ipcounter.de.ip
Unhandled options: ~script
Unhandled options: domain=~thedailybeast.com.ip
Unhandled options: domain=~skytide.ip
Unhandled options: domain=~skytide.ip
Unhandled options: domain=~skytide.ip
Unhandled options: domain=~skytide.ip
Unhandled options: domain=~skytide.ip
Unhandled options: domain=~skytide.ip
Unhandled options: domain=~skytide.ip
Unhandled options: domain=~sat24.com.ip
Unhandled options: domain=~stream5.tv.ip
Unhandled options: domain=~skytide.ip
Unhandled options: domain=~skytide.ip
Unhandled options: domain=~crosspixelmedia.ip
Unhandled options: domain=~gatehousenewsservice.com.ip
Unhandled options: xmlhttprequest
Unhandled options: object-subrequest
Unhandled options: object-subrequest
Unhandled options: object-subrequest
Unhandled options: object-subrequest
Unhandled options: object-subrequest
Unhandled options: domain=~yahoo.com
Unhandled options: domain=~exa-online.de.ip
Unhandled options: domain=~dasoertliche.de|~gelbeseiten.de
Unhandled options: domain=~quattroruote.ip
Unhandled options: ~other
Unhandled options: domain=cnet.com
Unhandled options: domain=haaretz.com
Unhandled options: domain=glam.com
Unhandled options: domain=doctorwhonews.net
Unhandled options: domain=feedcat.net
Unhandled options: object
Unhandled options: object
Unhandled options: object
Unhandled options: ~object-subrequest
Unhandled options: domain=sourceforge.net
Unhandled options: object-subrequest
Unhandled options: object
Unhandled options: object
Unhandled options: object
Unhandled options: ~xmlhttprequest
Unhandled options: object
Unhandled options: object
Unhandled options: object
Unhandled options: object
Unhandled options: object
Unhandled options: subdocument
Unhandled options: object
Unhandled options: object
Unhandled options: xmlhttprequest
Unhandled options: object-subrequest
Unhandled options: subdocument
Unhandled options: domain=bluray-disc.de
Unhandled options: domain=~sevenload.com.ip
Unhandled options: object-subrequest
Unhandled options: object-subrequest
Unhandled options: object-subrequest
Unhandled options: object
Unhandled options: domain=yonhapnews.co.kr
Unhandled options: donottrack, ~image
Unhandled options: donottrack, ~image
Unhandled options: domain=jacaranda.antraffic.mobi|m.traffic.jacarandafm.com
Unhandled options: domain=blog.cloudflare.com
Unhandled options: object-subrequest
Unhandled options: domain=readwriteweb.com
Unhandled options: object-subrequest, domain=cicispizza.com
Unhandled options: domain=cnettv.cnet.com|gamespot.com|tv.com
Unhandled options: domain=apps.facebook.com|g4tv.com
Unhandled options: object-subrequest
Unhandled options: object-subrequest
Unhandled options: object-subrequest, domain=sbs.com.au
Unhandled options: domain=menshealth.com|michaels.com|my.t-mobile.com
Unhandled options: object-subrequest, domain=abc.go.com|cbc.ca|edgesuite.net|espn.go.com
Unhandled options: domain=moddb.com
Unhandled options: xmlhttprequest
Unhandled options: domain=incgamers.com|qatarairways.com|stoli.com
Unhandled options: domain=login.skype.com
Unhandled options: domain=ancestry.com.au
Unhandled options: subdocument, domain=itworld.com
Unhandled options: subdocument, domain=itworld.com
Unhandled options: domain=autoblog.com
Unhandled options: domain=autoblog.com|mapquest.com|video.aol.com|www.aol.com
Unhandled options: domain=autoblog.com
Unhandled options: domain=bebo.com
Unhandled options: domain=bebo.com
Unhandled options: domain=ap.org
Unhandled options: object-subrequest, domain=cbs.com|grabnetworks.com
Unhandled options: domain=thenounproject.com
Unhandled options: domain=deviantart.com|linkinpark.com|mainstreet.com|ning.com|plixi.com|thedailybeast.com
Unhandled options: xmlhttprequest
Unhandled options: domain=breitbart.tv
Unhandled options: object-subrequest, domain=zap2it.com
Unhandled options: object-subrequest, domain=live.indiatimes.com
Unhandled options: object-subrequest
Unhandled options: object-subrequest
Unhandled options: subdocument, domain=mycokerewards.com
Unhandled options: domain=nydailynews.com
Unhandled options: domain=kaguma.com
Unhandled options: domain=tassimo.de
Unhandled options: domain=stylished.de
Unhandled options: object-subrequest, domain=galileo-videolexikon.de
Unhandled options: object-subrequest, domain=galileo-videolexikon.de
Unhandled options: domain=automatensuche.de
Unhandled options: object-subrequest, domain=web.de
Unhandled options: object-subrequest, domain=web.de
Unhandled options: domain=stylished.de
Unhandled options: domain=immowelt.de
Unhandled options: object-subrequest, domain=megatv.com
Unhandled options: domain=tvnwarszawa.pl
Unhandled options: xmlhttprequest
Cloning into 'https-everywhere'...
remote: Counting objects: 20265, done.
remote: Compressing objects: 100% (8374/8374), done.
remote: Total 20265 (delta 13038), reused 18289 (delta 11796)
Receiving objects: 100% (20265/20265), 2.70 MiB | 902 KiB/s, done.
Resolving deltas: 100% (13038/13038), done.
Traceback (most recent call last):
  File "./https_everywhere_import.py", line 18, in <module>
    from BeautifulSoup import BeautifulSoup
ImportError: No module named BeautifulSoup
make: **\* [privoxy/https_everywhere.action] Error 1

**Comment by jvasile** [comment]
Thanks much, Ale.  I will add beautifulsoup to the package.
