### ISSUE TITLE
depend on python-lxml

### ISSUE THREAD

**Issue by alelondon** [jvasile/freedombox-privoxy#2]
Unhandled options: xmlhttprequest
Cloning into 'https-everywhere'...
remote: Counting objects: 20308, done.
remote: Compressing objects: 100% (8416/8416), done.
remote: Total 20308 (delta 13064), reused 18288 (delta 11796)
Receiving objects: 100% (20308/20308), 2.71 MiB | 877 KiB/s, done.
Resolving deltas: 100% (13064/13064), done.
Traceback (most recent call last):
  File "./https_everywhere_import.py", line 19, in <module>
    from lxml import etree
ImportError: No module named lxml
make: **\* [privoxy/https_everywhere.action] Error 1

**Comment by jvasile** [comment]
Thanks for that.  I always forget those extra dependencies.
