### ISSUE TITLE
Cloning into 'git2changelog'... Permission denied (publickey).

### ISSUE THREAD

**Issue by alelondon** [jvasile/freedombox-privoxy#3]
After aptitude install python-beautifulsoup python-lxml

 make deb
--2012-01-28 12:17:05--  https://easylist-downloads.adblockplus.org/easyprivacy.txt
p11-kit: couldn't load module: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so: cannot open shared object file: No such file or directory
Resolving easylist-downloads.adblockplus.org (easylist-downloads.adblockplus.org)... 213.239.217.143
.....
.....
Unhandled options: object, object-subrequest
Cloning into 'git2changelog'...
Permission denied (publickey).
fatal: The remote end hung up unexpectedly
make: **\* [vendor/git2changelog/git2changelog.py] Error 128

maybe is a problem of  my config?
i ve got already some gnome-keyring warnings before,

**Comment by jvasile** [comment]
I replaced the git2changelog address in the Makefile.  Please give it
another shot.

-J

**Comment by alelondon** [comment]
I managed to skip this one by setting my github public key. But asked for passphrase.
Now it's as it should be.

**Comment by jvasile** [comment]
Ah, good.
