### ISSUE TITLE
make_deb.sh PRIVDIR setting not working

### ISSUE THREAD

**Issue by alelondon** [jvasile/freedombox-privoxy#4]
<pre>
:~/freedombox-privoxy$ make deb
--2012-01-29 15:25:18--  https://easylist-downloads.adblockplus.org/easyprivacy.txt
WARNING: gnome-keyring:: couldn't connect to: /tmp/keyring-KIKKX1/pkcs11: No such file or directory
Resolving easylist-downloads.adblockplus.org (easylist-downloads.adblockplus.org)... 213.239.217.143
Connecting to easylist-downloads.adblockplus.org (easylist-downloads.adblockplus.org)|213.239.217.143|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 101002 (99K) [text/plain]
Saving to: `easyprivacy.txt'

100%[======================================>] 101,002      643K/s   in 0.2s    

2012-01-29 15:25:22 (643 KB/s) - `easyprivacy.txt' saved [101002/101002]

Unhandled options: donottrack, ~image
Unhandled options: domain=~informer.com.ip
Unhandled ......
.....

Unhandled options: object, object-subrequest
Cloning into 'git2changelog'...
remote: Counting objects: 26, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 26 (delta 7), reused 22 (delta 3)
Receiving objects: 100% (26/26), 4.14 KiB, done.
Resolving deltas: 100% (7/7), done.
fatal: Path 'VERSION' exists on disk, but not in '9b4cf342910ba5e3e920f583c1326cf56de70bd4'.
./make_deb.sh
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: You must put some 'source' URIs in your sources.list
You might need to "apt-get build-dep privoxy" as root
ls: cannot access privoxy*: No such file or directory'
</pre>

```
   <=== strange! on interactive shell it works as expected!
```

<pre>
PRIVDIR =
FBOXDIR = freedombox-privoxy-3.0.19-1-4
cp: missing destination file operand after `freedombox-privoxy-3.0.19-1-4'
Try `cp --help' for more information.
ls: cannot access privoxy*: No such file or directory
head: cannot open `/debian/changelog' for reading: No such file or directory
cp: cannot stat `.orig.tar.gz': No such file or directory
./make_deb.sh: line 20: cd: freedombox-privoxy-3.0.19-1-4: No such file or directory
./make_deb.sh: line 21: dpatch: command not found
find: `Debian': No such file or directory
DEBDIR =
Adding patch config
sed: can't read /debian/patches/00list: No such file or directory
./make_deb.sh: line 33: /debian/patches/90_config.dpatch: No such file or directory
cat: /debian/patches/90_config.dpatch: No such file or directory
./make_deb.sh: line 35: /debian/patches/00list: No such file or directory
Adding patch match-all.action
sed: can't read /debian/patches/00list: No such file or directory
./make_deb.sh: line 33: /debian/patches/91_match-all.action.dpatch: No such file or directory
cat: /debian/patches/91_match-all.action.dpatch: No such file or directory
./make_deb.sh: line 35: /debian/patches/00list: No such file or directory
Adding patch default.action
sed: can't read /debian/patches/00list: No such file or directory
./make_deb.sh: line 33: /debian/patches/92_default.action.dpatch: No such file or directory
cat: /debian/patches/92_default.action.dpatch: No such file or directory
./make_deb.sh: line 35: /debian/patches/00list: No such file or directory
Adding patch default.filter
sed: can't read /debian/patches/00list: No such file or directory
./make_deb.sh: line 33: /debian/patches/93_default.filter.dpatch: No such file or directory
cat: /debian/patches/93_default.filter.dpatch: No such file or directory
./make_deb.sh: line 35: /debian/patches/00list: No such file or directory
Adding patch easyprivacy.action
sed: can't read /debian/patches/00list: No such file or directory
./make_deb.sh: line 33: /debian/patches/94_easyprivacy.action.dpatch: No such file or directory
cat: /debian/patches/94_easyprivacy.action.dpatch: No such file or directory
./make_deb.sh: line 35: /debian/patches/00list: No such file or directory
Adding patch easylist.action
sed: can't read /debian/patches/00list: No such file or directory
./make_deb.sh: line 33: /debian/patches/95_easylist.action.dpatch: No such file or directory
cat: /debian/patches/95_easylist.action.dpatch: No such file or directory
./make_deb.sh: line 35: /debian/patches/00list: No such file or directory
Adding patch https_everywhere.action
sed: can't read /debian/patches/00list: No such file or directory
./make_deb.sh: line 33: /debian/patches/96_https_everywhere.action.dpatch: No such file or directory
cat: /debian/patches/96_https_everywhere.action.dpatch: No such file or directory
./make_deb.sh: line 35: /debian/patches/00list: No such file or directory
Adding patch filters.c
sed: can't read /debian/patches/00list: No such file or directory
./make_deb.sh: line 33: /debian/patches/97_filters.c.dpatch: No such file or directory
cat: /debian/patches/97_filters.c.dpatch: No such file or directory
./make_deb.sh: line 35: /debian/patches/00list: No such file or directory
Updating changelog
cp: cannot stat `changelog': No such file or directory
cat: /debian/changelog: No such file or directory
mv: cannot move `changelog.debian' to `/debian/changelog': No such file or directory
Updating control
cp: cannot stat `privoxy/debian/control': No such file or directory
Updating rules
./make_deb.sh: line 55: pushd: /debian: No such file or directory
sed: can't read rules: No such file or directory
sed: can't read rules: No such file or directory
sed: can't read rules: No such file or directory
mv: cannot stat `init.d': No such file or directory
sed: can't read rules: No such file or directory
sed: can't read rules: No such file or directory
sed: can't read rules: No such file or directory
./make_deb.sh: line 63: popd: directory stack empty
Updating doc_base
./make_deb.sh: line 70: pushd: /debian: No such file or directory
sed: can't read doc-base.*: No such file or directory
./make_deb.sh: line 72: popd: directory stack empty
./make_deb.sh: line 99: cd: Debian/freedombox-privoxy-3.0.19-1-4: No such file or directory
./make_deb.sh: line 100: dpatch: command not found
make: *** [debian] Error 127
</pre>

**Comment by alelondon** [comment]
well... "<"pre> and "<"/pre> is not the best solution. I ll try to study better the github markup.

**Comment by jvasile** [comment]
That is quite odd.  There's a privoxy\* dir in both freedombox-privoxy
and freedombox-privoxy/Debian.  I pushed a version that does pwd if
PRIVDIR is blank.  Maybe that will shed some light.

**Comment by alelondon** [comment]
I'm sorry. Please revert your commit. It's not necessary. The problem was that my /etc/sources.list had deb-src repos commented out.
May this (even as obvious as it seems)be included in docs as required?
There was a hint in the output, may be a clearer error output when sources couldn't have been retrieved?

**Comment by jvasile** [comment]
Yes, I'll fix the docs.  And do something clearer in the script.  Thanks!
