### ISSUE TITLE
"only garbage in patch"

### ISSUE THREAD

**Issue by ghost** [jvasile/freedombox-privoxy#5]
applying patch 96_https_everywhere.action to ./ ...patch: ***\* Only garbage was found in the patch input.
 failed.
make: **\* [debian] Error 1

**Comment by alelondon** [comment]
Can't reproduce it here. Try deleting the whole freedombox-privoxy dir and git clone again?

**Comment by jvasile** [comment]
That's odd.  What's in the patch file in
freedombox-privoxy/Debian/freedombox-privoxy-*/debian/patches/96_https_everywhere.action
is it a valid patch?

**Comment by ghost** [comment]
That is what i find inside the patch:
luzer$ cat !$
cat 96_https_everywhere.action.dpatch
#! /bin/sh /usr/share/dpatch/dpatch-run
96_https_everywhere.action.dpatch by James Vasile james@jamesvasile.com
luzer$ pwd
/home/molloy/Data/Build/Apps/freedombox-privoxy/Debian/freedombox-privoxy-3.0.19-1-5/debian/patches
luzer$ 

I had to remove the hash-comment (#) in front of the line starting with 96, else it will formatted as upper case and bold, which looked very strange. In the file it is commented.

I tested this on several machines, 3, with different branches of Debian (stable, testing and unstable). 

Thanks

**Comment by jvasile** [comment]
I can't reproduce it.  That file is created by the "diff -urNad
${DEBDIR}/$1 privoxy/$1 > ${DEST}" line in make_deb.sh and for some
reason diff is finding no difference against the missing file.  My guess
is that the privoxy/https_everywhere.action is missing or empty.  What
happens when you do "make clean; make privoxy/https_everywhere.action"?

Or do it manually:

```
./https_everywhere_import.py > privoxy/https_everywhere.action
```

Thanks,
James

**Comment by ghost** [comment]
running: 
./https_everywhere_import.py > privoxy/https_everywhere.action
did work.

It gave me an error (which i did not write down, and i can't reproduce it on stable),  i then ran "make deb" again, and it worked successfully. 
The source of my problem is probably a simple user error i made somewhere. Thanks for the help.

**Comment by jvasile** [comment]
I think the source of your problem might have been a lack of python-lxml.  I've noted to install it in the README.  Thanks!
